Repository n1md7/GG-Soft-Quoridor, pull requests merged in 2025-09, with the labels that each got.

#55 Fixed some CSS issue, created central import for css files.
  .stylelintrc.json
  package.json
  src/main.tsx
  src/views/GamePlay.tsx
  src/views/InitialView.tsx
  src/views/LobbyView.tsx
  styles/animations.css
  styles/fonts.css
  styles/gameplay-view.css
  styles/index.css
  styles/initial-view.css
  styles/lobby-view.css
  styles/main.css
Labels: to fix

#56 conflict with bun
  bun.lock
  bun.lockb
Labels: bug

#58 fix leaderboard display
  src/views/LobbyView.tsx
  styles/lobby-view.css
Labels: enhancement

#69 chore: music and sound-effects
  public/sounds/background.mp3
  public/sounds/mouse-click.mp3
  public/sounds/pawn-move.mp3
  public/sounds/player-error.mp3
  public/sounds/player-win.mp3
  public/sounds/wall-place.mp3
  src/components/game/Experience.tsx
  src/components/game/pawns/Pawn.tsx
  src/components/game/walls/Wall.tsx
  src/core/classes/sound.class.ts
  src/core/entities/player/player.class.ts
  src/core/game.class.ts
  src/core/managers/event.manager.ts
  src/core/managers/sound.manager.ts
  src/core/states/play.state.ts
Labels: enhancement, to review

#72 back button for sound settings
  src/App.tsx
  src/components/ui/GameSettings.tsx
  src/views/GamePlay.tsx
  src/views/InitialView.tsx
  src/views/LobbyView.tsx
  styles/initial-view.css
  styles/lobby-view.css
  styles/main.css
Labels: enhancement, ui / ux, to do

#73 68 create market and powers
  src/components/game/Market.tsx
  src/components/game/board/Board.tsx
  src/components/hooks/useSettings.ts
  src/components/hooks/useStorage.ts
  src/core/classes/inventory-item.class.ts
  src/core/classes/inventory.class.ts
  src/core/classes/market-item.class.ts
  src/core/classes/market.class.ts
  src/core/classes/power.class.ts
  src/core/enums/power.enum.ts
  src/core/game.class.ts
  src/core/interfaces/store.interface.ts
  src/core/managers/reward.manager.ts
  src/core/managers/storage.manager.ts
Labels: to review

#86 78 create power undo
  src/components/game/board/Board.tsx
  src/components/game/walls/Walls.tsx
  src/components/game/walls/wall.type.ts
  src/components/hooks/useStatistics.ts
  src/components/hooks/useWalls.ts
  src/core/entities/abstract/character.class.ts
  src/core/entities/abstract/game.mode.ts
  src/core/entities/computer/computer.class.ts
  src/core/entities/player/actions/abstract.ts
  src/core/entities/player/actions/composition.ts
  src/core/entities/player/actions/strategies/pawn.action.ts
  src/core/entities/player/actions/strategies/wall.action.ts
  src/core/entities/player/coordinates.class.ts
  src/core/entities/player/player.class.ts
  src/core/entities/player/statistics.class.ts
  src/core/game.class.ts
  src/core/managers/grid.manager.ts
  src/core/managers/mode.manager.ts
  src/core/managers/performance.manager.ts
  src/core/managers/reward.manager.ts
  src/core/modes/easy.mode.ts
  src/core/modes/hard.mode.ts
  src/core/modes/medium.mode.ts
Labels: enhancement, gameplay, to review

#87 feat: block opponent to move
  src/components/game/board/Board.tsx
  src/core/entities/computer/computer.class.ts
  src/core/entities/computer/skip.manager.ts
Labels: enhancement, gameplay

#88 feat: extra wall power
  src/components/game/board/Board.tsx
  src/components/game/walls/Wall.tsx
  src/components/game/walls/Walls.tsx
  src/components/game/walls/wall.type.ts
  src/components/hooks/useWalls.ts
Labels: gameplay
